ERROR | 2023-11-05 22:11:48,744 | MainProcess | [WinError 10054] An existing connection was forcibly closed by the remote host
Traceback (most recent call last):
  File "D:\Python\Networks with Nir\Class excercise 2\server.py", line 87, in main
    match client_socket.recv(MAX_PACKET).decode().upper():
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
ERROR | 2023-11-05 22:12:22,793 | MainProcess | a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:\Python\Networks with Nir\Class excercise 2\server.py", line 102, in main
    Commands.comm_exit(client_socket)
  File "D:\Python\Networks with Nir\Class excercise 2\server.py", line 64, in comm_exit
    client_socket.send("Disconnecting...")
TypeError: a bytes-like object is required, not 'str'
ERROR | 2023-11-05 22:13:38,553 | MainProcess | a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "D:\Python\Networks with Nir\Class excercise 2\server.py", line 102, in main
    Commands.comm_exit(client_socket)
  File "D:\Python\Networks with Nir\Class excercise 2\server.py", line 64, in comm_exit
    client_socket.send("Disconnecting...")
TypeError: a bytes-like object is required, not 'str'
ERROR | 2023-11-05 22:15:35,329 | MainProcess | [WinError 10038] An operation was attempted on something that is not a socket
Traceback (most recent call last):
  File "D:\Python\Networks with Nir\Class excercise 2\server.py", line 87, in main
    match client_socket.recv(MAX_PACKET).decode().upper():
OSError: [WinError 10038] An operation was attempted on something that is not a socket
ERROR | 2023-11-05 22:19:42,809 | MainProcess | [WinError 10022] An invalid argument was supplied
Traceback (most recent call last):
  File "D:\Python\Networks with Nir\Class excercise 2\server.py", line 71, in client_handle
    socket.bind((IP, PORT))
OSError: [WinError 10022] An invalid argument was supplied
ERROR | 2023-11-05 22:19:42,809 | MainProcess | [WinError 10038] An operation was attempted on something that is not a socket
Traceback (most recent call last):
  File "D:\Python\Networks with Nir\Class excercise 2\server.py", line 83, in client_handle
    match client_socket.recv(MAX_PACKET).decode().upper():
OSError: [WinError 10038] An operation was attempted on something that is not a socket
